services:
  mypostgres:
    container_name: mypostgres16
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: course_management
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=postgres pg_isready -U postgres -h postgres" ]
      interval: 10s
      timeout: 5s
      retries: 50
volumes:
  db_data: