server:
  port: 8080
spring:
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/course_management
    locations: classpath:db/migration
    default-schema: course_management
  application:
    name: basic-crud
  datasource:
    url: jdbc:postgresql://localhost:5432/course_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: course_management
