server:
  port: 8080
spring:
  application:
    name: basic-crud
  datasource:
    url: jdbc:postgresql://localhost:5432/course_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
